# Generated by Django 3.2 on 2022-08-09 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('pontos', models.IntegerField(blank=True, null=True, verbose_name='Pontos')),
            ],
        ),
        migrations.CreateModel(
            name='Negociar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Negociado')),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(max_length=15, verbose_name='Sexo')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('infectado', models.BooleanField(default=False, verbose_name='Infectado')),
            ],
        ),
        migrations.CreateModel(
            name='TrocarReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('item_troca', models.CharField(choices=[('1', 'Trocar'), ('2', 'Receber')], default=1, max_length=50, verbose_name='Item Troca')),
                ('itens', models.ManyToManyField(related_name='itens', to='api.Itens')),
                ('negociar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociar', to='api.negociar', verbose_name='Negoicar')),
            ],
        ),
        migrations.CreateModel(
            name='SobreviventeInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_itens', to='api.itens', verbose_name='Item')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_sobreviventes', to='api.sobrevivente', verbose_name='Sobrevivente')),
            ],
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='inventario',
            field=models.ManyToManyField(related_name='sobrevivente_itens', through='api.SobreviventeInventario', to='api.Itens'),
        ),
        migrations.AddField(
            model_name='negociar',
            name='sobrevivente_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivente_receber', to='api.sobrevivente', verbose_name='Sobrevivente Receber'),
        ),
        migrations.AddField(
            model_name='negociar',
            name='sobrevivente_trocar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivente_trocar', to='api.sobrevivente', verbose_name='Sobrevivente Trocar'),
        ),
        migrations.CreateModel(
            name='Sinalizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivente', to='api.sobrevivente', verbose_name='Sobrevivente')),
                ('sobrevivente_infectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivente_infectado', to='api.sobrevivente', verbose_name='Sobrevivente Infectado')),
            ],
            options={
                'unique_together': {('sobrevivente', 'sobrevivente_infectado')},
            },
        ),
    ]
